---
title: "Combine and plot ORA results and compare genome choice effects "
author: "CIG @ MGI"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
rm(list = ls())
set.seed(0)

knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/Users/juanmacias/Library/CloudStorage/Box-Box/LawsonLab/JuanMacias/Postdoc/Ayate_Dev/Ayate_chrM/")

rm(list = ls())
set.seed(0)

require("ggplot2")
require("cowplot")
require("viridis")
require("reshape2")
require("dplyr")
require("tidyverse")

source("/Users/juanmacias/Library/CloudStorage/Box-Box/LawsonLab/JuanMacias/Misc_Code/CS_Aesthetic.R")

theme_set(theme_cowplot())
```

```{r import cross edit distance matrix}
# Import cross edit distance matrix
cross_edit_distance_matrix <- read.table("/Users/juanmacias/Library/CloudStorage/Box-Box/LawsonLab/JuanMacias/Postdoc/Ayate_Dev/Ayate_chrM/Mat_Ref_dist.transformed.tsv", header = FALSE)

# Convert to matrix
cross_edit_distance_matrix<-as.matrix(cross_edit_distance_matrix)
colnames(cross_edit_distance_matrix)<-NULL

# Threshold matrix
cross_edit_distance_matrix<-cross_edit_distance_matrix>(1/(2^6))

# Convert to long data frame to plot heatmap with ggplot
cross_edit_distance_matrix_long<-melt(cross_edit_distance_matrix)
colnames(cross_edit_distance_matrix_long)<-c("Query", "Reference", "Distance")
```

```{r plot cross edit distance matrix}
# Plot cross edit distance matrix
cross_edit_distance_matrix_plot<-ggplot(cross_edit_distance_matrix_long, aes(x=Query, y=Reference, fill=Distance))+
  geom_tile()+
  scale_fill_viridis_d()+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  theme(legend.position = "none")+
  scale_y_continuous(position = "right", limits = c(0,max(cross_edit_distance_matrix_long$Reference)+1), expand = c(0,0)) +
  scale_x_continuous(position = "top", limits = c(0,max(cross_edit_distance_matrix_long$Query)+1), expand = c(0,0))+
  CS.THEME

```

```{r import self distance matrices}
# Import Query Query edit distance matrix
QueryQuery_edit_distance_matrix <- read.table("/Users/juanmacias/Library/CloudStorage/Box-Box/LawsonLab/JuanMacias/Postdoc/Ayate_Dev/Ayate_chrM/Mat_Mat_dist.transformed.tsv", header = FALSE)

# Convert to matrix
QueryQuery_edit_distance_matrix<-as.matrix(QueryQuery_edit_distance_matrix)
colnames(QueryQuery_edit_distance_matrix)<-NULL

# Only keep the upper triangle
QueryQuery_edit_distance_matrix[lower.tri(QueryQuery_edit_distance_matrix)]<-NA

# Threshold matrix
QueryQuery_edit_distance_matrix<-QueryQuery_edit_distance_matrix>(1/(2^6))

# Convert to long data frame to plot heatmap with ggplot
QueryQuery_edit_distance_matrix_long<-melt(QueryQuery_edit_distance_matrix)
colnames(QueryQuery_edit_distance_matrix_long)<-c("QueryA", "QueryB", "Distance")

# Import Reference Reference edit distance matrix
ReferenceReference_edit_distance_matrix <- read.table("/Users/juanmacias/Library/CloudStorage/Box-Box/LawsonLab/JuanMacias/Postdoc/Ayate_Dev/Ayate_chrM/Ref_Ref_dist.transformed.tsv", header = FALSE)

# Convert to matrix
ReferenceReference_edit_distance_matrix<-as.matrix(ReferenceReference_edit_distance_matrix)
colnames(ReferenceReference_edit_distance_matrix)<-NULL

# Keep only the lower triangle
ReferenceReference_edit_distance_matrix[upper.tri(ReferenceReference_edit_distance_matrix)]<-NA

# Threshold matrix
ReferenceReference_edit_distance_matrix<-ReferenceReference_edit_distance_matrix>(1/(2^6))

# Convert to long data frame to plot heatmap with ggplot
ReferenceReference_edit_distance_matrix_long<-melt(ReferenceReference_edit_distance_matrix)
colnames(ReferenceReference_edit_distance_matrix_long)<-c("ReferenceA", "ReferenceB", "Distance")
```

```{r plot self distance matrices}
# Plot Query Query edit distance matrix
QueryQuery_edit_distance_matrix_plot<-ggplot(QueryQuery_edit_distance_matrix_long, aes(x=QueryA, y=QueryB, fill=Distance))+
  geom_tile()+
  scale_fill_viridis_d()+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  scale_y_continuous(limits = c(0,max(QueryQuery_edit_distance_matrix_long$QueryA)+1), expand = c(0,0)) +
  scale_x_continuous(position = "top", limits = c(0,max(QueryQuery_edit_distance_matrix_long$QueryA)+1), expand = c(0,0))+
  ylab("Query")+
  xlab("")+
  theme(legend.position = "none")+
  theme(
    axis.ticks.x = element_blank(),  # Remove x-axis ticks
    axis.text.x = element_blank()    # Remove x-axis labels
  )+
  CS.THEME

# Plot Reference Reference edit distance matrix, no axis
ReferenceReference_edit_distance_matrix_plot<-ggplot(ReferenceReference_edit_distance_matrix_long, aes(x=ReferenceA, y=ReferenceB, fill=Distance))+
  geom_tile()+
  scale_fill_viridis_d()+
  scale_y_continuous(position = "right", limits = c(0,max(ReferenceReference_edit_distance_matrix_long$ReferenceA)+1), expand = c(0,0)) +
  scale_x_continuous(position = "bottom", limits = c(0,max(ReferenceReference_edit_distance_matrix_long$ReferenceA)+1), expand = c(0,0))+
  ylab("")+
  xlab("Reference")+
  theme(legend.position = "none")+
  theme(
    axis.ticks.y = element_blank(),  # Remove y-axis ticks
    axis.text.y = element_blank()    # Remove y-axis labels
  )+
  CS.THEME

# blank plot
blank_plot<-ggplot()+theme_void()

# Combine plots

# Adjust plot margins for each plot to reduce excessive space
cross_edit_distance_matrix_plot <- cross_edit_distance_matrix_plot +
  theme(plot.margin = unit(c(0, 0, 0, 0), "cm"))

QueryQuery_edit_distance_matrix_plot <- QueryQuery_edit_distance_matrix_plot +
  theme(plot.margin = unit(c(0, 0, 0, 0), "cm"))

ReferenceReference_edit_distance_matrix_plot <- ReferenceReference_edit_distance_matrix_plot +
  theme(plot.margin = unit(c(0, 0, 0, 0), "cm"))

blank_plot <- blank_plot +
  theme(plot.margin = unit(c(0, 0, 0, 0), "cm"))

Panel<-plot_grid(
  ReferenceReference_edit_distance_matrix_plot,
  cross_edit_distance_matrix_plot,
  blank_plot,
  QueryQuery_edit_distance_matrix_plot,
  ncol = 2,
  align = "hv",
  axis = "tblr",
  rel_widths = c(1, 1),
  rel_heights = c(1, 1),
  greedy = TRUE
)
```

```{r plot panel, include=TRUE, fig.width=12, fig.height=12}
Panel
```








